class UserStates:
    AUTHORIZE_STATE = "AuthorizeState"
    AWAITING_AUTHORIZATION_STATE = "AwaitingAuthorizationState"
    START_STATE = "StartState"
    SELECT_PROBLEM_STATE = "SelectProblemState"
    ADD_PROBLEM_STATE = "AddCustomProblemState"
    DOCTOR_MENU_STATE = "DoctorMenuState"
    LANGUAGE_SELECTION_STATE = "LanguageSelectionState"
    SELECT_CONNECTION_STATE = "SelectConnectionState"
    PUBLIC_AWAITING_APPROVE_STATE = "PublicAwaitingApproveState"
    FINISH_CONVERSATION_STATE = "FinishConversationState"
    SELECT_APPEAL_STATE = "SelectAppealState"
    EXAMINE_APPEAL_STATE = "ExamineAppealState"
